app/controllers/download.py
from flask import Blueprint, send_file, send_from_directory
import os
import pathlib


controller = Blueprint('download', __name__)


@controller.route('/files/<file_name>', methods=['GET'])
def download(file_name):
    root_path = pathlib.Path(__file__).resolve().parents[1]
    full_path = os.path.join(root_path, 'files')
    return send_from_directory(full_path, filename=file_name)

app/controllers/home.py
from flask import Blueprint, render_template, request, redirect

controller = Blueprint('home', __name__)


@controller.route('/')
def index():
    return render_template("index.html", nofooternav=True)


@controller.route('/hello')
def hello_world():
    team_name = DemoParser.our_team_name()
    return render_template('hello.html', team_name=team_name)

app/controllers/jobs.py
from flask import Blueprint, render_template, current_app, request, redirect, url_for, flash

from models.scrape_job import ScrapeJob
from models.job_attr import JobStatus
import hashlib

controller = Blueprint('jobs', __name__)


def short_hash(value, digits):
    value = str(value)

    return hashlib.md5(value.encode('utf-8')).hexdigest()[:digits]


@controller.route('/jobs', methods=['GET'])
def index():
    jobs = ScrapeJob.query.order_by(ScrapeJob.sys_created_on.desc()).all()
    return render_template(
        "jobs/index.html", 
        jobs=jobs, 
        hash=short_hash, 
        JobStatus=JobStatus)


@controller.route('/job/<job_id>', methods=['GET'])
def detail(job_id):
    referrer = request.referrer
    job = ScrapeJob.query.filter_by(id=job_id).first()
    if job != None:
        file_name = None
        if job.file:
            file_name = job.file.path.split("/")[-1]
        return render_template(
            "jobs/detail.html",
            job=job,
            JobStatus=JobStatus,
            file_name=file_name)
    else:
        path = referrer if referrer else url_for('jobs.index')
        flash('Job does not exist', 'error')
        return redirect(path)

app/templates/jobs/detail.html
{% extends "base.html" %} {% block body %}

<div class="container">
    <div class="row bg-3">
        <div class="col-md-6 col-md-offset-3">
            {% if job.status == JobStatus.FINISHED %}
            <div class="panel panel-success">
                {% elif job.status == JobStatus.FAILED %}
                <div class="panel panel-danger">
                    {% else %}
                    <div class="panel panel-primary"></div>
                    {% endif %}
                    <div class="panel-heading text-center">Your job is {{ job.status }}</div>
                    <div class="panel-body">
                        {% if job.file == None and job.status == JobStatus.FINISHED %}
                        <h3>No CSV file generated. Please check the input.</h3>
                        {% endif %}

                        <p><b>Job Type</b>: {{ job.jobType }}</p>
                        {% for k, v in job.detail_dict().items() %}
                        <p><b>{{ k | capitalize }}</b>: {{ v }}</p>
                        {% endfor %}

                        <p><b>Start Time</b>: {{ job.sys_created_on }}</p>

                        {% if job.sys_updated_on != None %}
                        <p><b>End Time</b>: {{ job.sys_updated_on }}</p>
                        {% endif %} {% if job.status == JobStatus.RUNNING %}
                        <div class="lds-dual-ring"></div>
                        {% elif file_name != None %}
                        <a href="{{ url_for('download.download', file_name=file_name) }}" class="btn btn-success">Download CSV</a> {% endif %}
                    </div>
                    <div class="panel-footer text-center">
                        <a href="{{ url_for('home.index') }}">Go Back</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/jobs/index.html
{% extends "base.html" %} {% block body %}

{% with errors = get_flashed_messages(with_categories=true) %}
  {% if errors %}
    <div class="container">
    {% for category, error in errors %}
        <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}

<div class="container h-100">
    <div class="d-flex h-100">
        <h2>All Jobs</h2>

        <table class="table">
            <tr>
                <th>ID</th>
                <th>Type</th>
                <th>Info</th>
                <th>Status</th>
                <th>Creation time</th>
            </tr>

            {% for job in jobs %}
            <tr>
                <td><a href="{{ url_for('jobs.detail', job_id=job.id) }}">{{ hash(job.id, 8) }}</a> </td>
                <td>{{ job.jobType }}</td>
                <td>
                    {% for k, v in job.detail_dict().items() %}
                    <b>{{ k | capitalize }}</b>: {{ v }}<br /> {% endfor %}
                </td>
                <td>
                    {% if job.status == JobStatus.FINISHED %}
                    <span class="label label-success">{{ job.status | capitalize }}</span> {% elif job.status == JobStatus.FAILED %}
                    <span class="label label-danger">{{ job.status | capitalize }}</span> {% else %}
                    <span>{{ job.status | capitalize }}</span> {% endif %}
                </td>
                <td>{{ job.sys_created_on }}</td>
            </tr>
            {% endfor %}

        </table>
    </div>
</div>

{% endblock %}