app/controllers/api.py
from models.scrape_job import ScrapeJob
from models.job_attr import JobType
from flask import Blueprint, render_template, request, redirect, url_for
controller = Blueprint('api', __name__ )


@controller.route('/api', methods=['GET'])
def api():
    return render_template("api.html")

@controller.route('/api', methods=['POST'])
def create_api_job():
    json_format = request.form['json_format']
    url = request.form['url']

    if json_format == None or json_format == "":
        json_format = "flat"

    extra = {
        "url": url,
        "json_format": json_format
    }

    job = ScrapeJob(JobType.API, url, extra)
    if job:
        job.run()
        return redirect(url_for('jobs.detail', job_id=job.id))
    else:
        return render_template("api.html", error="Parsing job was not created.")

app/controllers/form.py
from lib.parsers.form_parser import FormParser
from flask import Blueprint, render_template, request, redirect, url_for, flash
from db import db
from models.scrape_file import ScrapeFile
from models.scrape_job import ScrapeJob
from models.job_attr import JobType
from lib.parsers.form_parser import FormParser

controller = Blueprint('form', __name__)


@controller.route('/form', methods=['GET'])
def form():
    form_names = FormParser.TEMPLATE_NAMES
    return render_template("form.html", form_names=form_names)


@controller.route('/form', methods=['POST'])
def create_form_job():
    file = request.files['file']
    form_name = request.form['form-type']

    if file.filename:
        if '.pdf' not in file.filename:
            return render_template("form.html", error="JOB FAILED. ERROR INFO: File type is not supported.")
        sf = ScrapeFile(file)

        extra = {
            'file name': file.filename,
            'form name': form_name
        }
        job = ScrapeJob(JobType.FORM, sf.id, extra)

        db.session.add(sf)
        db.session.add(job)
        db.session.commit()

        # Kick off the Job Now
        job.run()

        return redirect(url_for('jobs.detail', job_id=job.id))

    else:
        flash("Job Failed. ERROR INFO: NoFileFoundError. Upload the file and try again.", 'error')
        return redirect('form.form')

app/controllers/home.py
from flask import Blueprint, render_template, request, redirect

controller = Blueprint('home', __name__)


@controller.route('/')
def index():
    return render_template("index.html", nofooternav=True)


@controller.route('/hello')
def hello_world():
    team_name = DemoParser.our_team_name()
    return render_template('hello.html', team_name=team_name)

app/controllers/html.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.job_attr import JobType
from models.scrape_job import ScrapeJob

controller = Blueprint('html', __name__)

@controller.route('/html', methods=['GET'])
def html():
    return render_template("html.html")

@controller.route('/html', methods=['POST'])
def create_html_job():
    url = request.form['url']
    if url == '':
        return render_template("html.html", error="FAILED. ERROR INFO: No url found.")

    extra = {
        "url": url
    }

    job = ScrapeJob(JobType.HTML, url, extra)
    if job:
        job.run()
        return redirect(url_for('jobs.detail', job_id=job.id))
    else:
        return render_template("html.html", error="Parsing job was not created.")

app/controllers/pdf.py
from flask import Blueprint, render_template, request, redirect, url_for
from db import db
from models.scrape_file import ScrapeFile
from models.scrape_job import ScrapeJob
from models.job_attr import JobType

controller = Blueprint('pdf', __name__)


@controller.route('/pdf', methods=['GET'])
def pdf():
    return render_template("pdf.html")


@controller.route('/pdf', methods=['POST'])
def create_pdf_job():
    file = request.files['file']

    if file.filename:
        sf = ScrapeFile(file)

        extra = {
            'file name': file.filename
        }

        job = ScrapeJob(JobType.PDF, sf.id, extra)

        db.session.add(sf)
        db.session.add(job)
        db.session.commit()

        # Kick off the Job Now
        job.run()

        return redirect(url_for('jobs.detail', job_id=job.id))
    else:
        return render_template("pdf.pdf", error="Parsing job was not created.")

app/templates/api.html
{% extends "base.html" %} {% block body %}
    <script src="{{ url_for('static', filename='js/api.js') }}"></script>
    <div class="container movedown">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h5>API</h5>
                    </div>
                    <div class="panel-body">
                        <form id="form_search" onsubmit="return apiCall(this)" method="post">
                            <div class="form-group">
                                <label for="url">URL</label>
                                <input type="text" name="url" id="api_url" class="form-control">
                            </div>

                            <div class="form-group form-ratio">
                                <label for="Output Style"></label>
                                <input type="radio" name="json_format" id="flat" value="flat" checked>
                                <label>Flat</label>
                                <input type="radio" name="json_format" id="structured" value="structured">
                                <label>Structured</label>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Convert CSV" class="btn btn-success btn-block">
                            </div>

                            <div class="form-group">
                                <input type="button" value="Go back" onclick="history.back()" class="btn btn-default btn-block">
                                <div id="data-link"></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>DataScrapper</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css')}}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('home.index') }}">DataScrapper</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('jobs.index') }}">HISTORY</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div>
        <div class="container">
            {% if error is defined %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endif %} {% if info is defined %}
            <div class="alert alert-info">{{ info }}</div>
            {% endif %}
        </div>
    </div>


    <!-- banner -->
    {% if self.banner() %}
    <div class="container-fluid bg-1 text-center content">
        {% block banner %}{% endblock %}
    </div>
    {% endif %}

    <!-- First Container -->
    {% if self.body() %}
    <div class="container-fluid content">
        {% block body %}{% endblock %}
    </div>
    {% endif %}


    <!-- Footer -->
    <footer class="panel-footer bg-4 text-center">
        <p>TEAM HZ-TASK | Health Informatics | Fall 2020</p>
        {% if not nofooternav is defined %}
        <p>
            <ul class="list-inline footer-navbar" id="footer-navbar">
                <li><a href="{{ url_for('form.form') }}">Form</a></li>
                <li><a href="{{ url_for('api.api') }}">API</a></li>
                <li><a href="{{ url_for('html.html') }}">HTML</a></li>
                <li><a href="{{ url_for('pdf.pdf') }}">PDF</a></li>
            </ul>
        </p>
        {% endif %}
    </footer>
    <script src="{{ url_for('static', filename='js/api.js')}}"></script>
</body>

</html>

app/templates/form.html
{% extends "base.html" %} {% block body %}
<div class="container movedown">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h5>FORM</h5>
                </div>
                <div class="panel-body">
                    <form id="form_search" action="{{ url_for('form.create_form_job') }}" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="form-type">Form type</label>
                            <select name="form-type" class="form-control">
                                {% for alias, fullname in form_names.items() %}
                                <option value="{{ alias }}">{{ fullname }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="btn btn-success btn-file btn-block">
                                    Upload PDF file<input type="file" name="file" style="display: none;">
                                </label>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Convert CSV" class="btn btn-success btn-block">
                        </div>

                        <div class="form-group">
                            <input type="button" value="Go back" onclick="history.back()" class="btn btn-default btn-block">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/hello.html
Hello, this is Team {{ team_name }}!

app/templates/html.html
{% extends "base.html" %} {% block body %}
    <div class="container movedown">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h5>HTML</h5>
                    </div>
                    <div class="panel-body">
                        <form id="form_search" action="{{ url_for('html.create_html_job') }}" method="post">
                            <div class="form-group">
                                <label for="url">URL</label>
                                <input type="text" name="url" class="form-control">
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Convert CSV" class="btn btn-success btn-block">
                            </div>

                            <div class="form-group">
                                <input type="button" value="Go back" onclick="history.back()" class="btn btn-default btn-block">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block banner %}
<div class="container bg-3 movedown">
    <div class="row bg-3 home-cards">
        <div class="col-md-10 col-md-offset-1">
            <div class="col-sm-6">
                <div class="panel panel-success">
                    <div class="panel-heading">Form</div>
                    <div class="panel-body">
                        Parse medical forms in PDF files using pre-define form template.
                    </div>
                    <div class="panel-footer">
                        <a href="{{ url_for('form.form') }}" class="btn btn-success btn-block"><i class="fab fa-wpforms"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="panel panel-success">
                    <div class="panel-heading">API</div>
                    <div class="panel-body">
                        Parse API response from JSON format into CSV files.
                    </div>
                    <div class="panel-footer">
                        <a href="{{ url_for('api.api') }}" class="btn btn-success btn-block"><i class="fas fa-code"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-10 col-md-offset-1">
            <div class="col-sm-6">
                <div class="panel panel-success">
                    <div class="panel-heading">HTML</div>
                    <div class="panel-body">
                        Parse HTML table into CSV files.
                    </div>
                    <div class="panel-footer">
                        <a href="{{ url_for('html.html') }}" class="btn btn-success btn-block"><i class="fas fa-table"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="panel panel-success">
                    <div class="panel-heading">PDF</div>
                    <div class="panel-body">
                        Parse generic tables or forms inside PDF files into CSV files.
                    </div>
                    <div class="panel-footer">
                        <a href="{{ url_for('pdf.pdf') }}" class="btn btn-success btn-block"><i class="far fa-file-pdf"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .panel-body {
        min-height:
    }
</style>
{% endblock %}

app/templates/pdf.html
{% extends "base.html" %} {% block body %}
<div class="container movedown">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h5>PDF</h5>
                </div>
                <div class="panel-body">
                    <form id="form_search" action="{{ url_for('pdf.create_pdf_job') }}" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label class="btn btn-success btn-file btn-block">
                                    Upload PDF file<input type="file" name="file" style="display: none;">
                                </label>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Convert CSV" class="btn btn-success btn-block">
                        </div>

                        <div class="form-group">
                            <input type="button" value="Go back" onclick="history.back()" class="btn btn-default btn-block">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}